### PR TITLE
Add async mode for raw()

### PR DESCRIPTION
**Pull request by timjrobinson**
I was originally going to add a callback for every function but I only need to use raw() and need it async (all node I/O should be done async if possible), and modifying every function got messy.

### CODE REVIEW

**Comment by jub3i** [comment]
@timjrobinson Thanks for the PR :) I updated the npm repo (with your changes) to v1.0.5 too.

Since you where only after `raw()`, the module [procfs](https://www.npmjs.com/package/procfs-stats) on npm might be of interest to you.

**Comment by timjrobinson** [comment]
Thanks! I do think it should be bumped to v1.1.0 though as there is an API change.

**Comment by jub3i** [comment]
I thought about that, but its not a breaking change (all existing code will still work) since we only added an optional parameter.

**Comment by timjrobinson** [comment]
Yea in semver (http://semver.org/) minor revisions are supposed to be used for backwards compatible changes. Patch's are only for bug fixes without any API changes.

**Comment by jub3i** [comment]
oh im being an idiot, shoulda bumped the minor :)

**Comment by timjrobinson** [comment]
all good :) Not too many people use this package but good to keep in mind for future.

**Pull request merged**
